// using ids for connections to allow for easier serialization and deserialization

export type CircuitElement = {
  id: string;
  x: number;
  y: number;
  nodes: Node[];
  type: string;
  properties?: {
    voltage?: number; // for power sources like batteries
    resistance?: number; // all components can have resistance
    ratio?: number; // for potentiometers, the ratio of resistance
    mode?: "voltage" | "current"; // for multimeters, can be voltage or current mode
  };
  computed?: {
    current?: number; // computed current through the element
    voltage?: number; // computed voltage across the element
    power?: number; // computed power consumed or generated by the element
    measurement?: number; // Specific reading for multimeter
  };
  controller?: {
    [key: string]: any;
  };
};

export type Wire = {
  toNodeId: string;
  fromNodeId: string;
  id: string;
  resistance?: number;
  color?: string; // Optional color for the wire
  joints: { x: number; y: number }[];
};

export type Node = {
  id: string;
  x: number;
  y: number;
  parentId: string;
  polarity?: "positive" | "negative"; // Optional polarity for the node
};

export type Size =
  | { width: number; height: number; radius?: never }
  | { radius: number; width?: never; height?: never };

export type EditingWire = {
  wireId: string;
  end: "from" | "to";
};

export type CircuitElementProps = {
  type: string;
  idNumber: number;
  pos: { x: number; y: number };
  properties?: {
    resistance?: number;
    voltage?: number;
    ratio?: number;
  };
};

export type PaletteElementType =
  | "lightbulb"
  | "battery"
  | "resistor"
  | "multimeter"
  | "potentiometer"
  | "led"
  | "microbit";

export type PropertiesPanelProps = {
  selectedElement: CircuitElement | null;
  wires: Wire[];
  getNodeById: (id: string) => Node | undefined;
  onElementEdit: (
    updatedElement: CircuitElement,
    deleteElement: boolean
  ) => void;
  onWireEdit: (updatedWire: Wire, deleteElement: boolean) => void;
  onEditWireSelect?: (wire: Wire) => void;
  setOpenCodeEditor: (open: boolean) => void;
};
